name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'        
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
  workflow_dispatch:      # ✅ Manual trigger option

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    # will set it in github Actions secrets and variables
    env:
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}
      LOCATION: ${{ secrets.LOCATION }}
      RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}-dev-${{ secrets.LOCATION }}-01
      FRONTEND_IMAGE: frontend
      BACKEND_IMAGE: backend
      CONTAINERAPPS_ENVIRONMENT: ${{ secrets.CONTAINERAPPS_ENVIRONMENT }}-dev-${{ secrets.LOCATION }}-01
      FRONTEND_APP_NAME: ${{ secrets.FRONTEND_APP_NAME }}-dev-${{ secrets.LOCATION }}-01
      BACKEND_APP_NAME: ${{ secrets.BACKEND_APP_NAME }}-dev-${{ secrets.BACKEND_APP_NAME }}-01

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $GHCR_REPO/$FRONTEND_IMAGE:latest ./app/frontend
          docker push $GHCR_REPO/$FRONTEND_IMAGE:latest

      - name: Build & Push Backend Image
        run: |
          docker build -t $GHCR_REPO/$BACKEND_IMAGE:latest ./app/backend
          docker push $GHCR_REPO/$BACKEND_IMAGE:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Backend Container App with New Image
        run: |
          az containerapp update \
            --name $BACKEND_APP_NAME \
            --resource-group $RESOURCE_GROUP_NAME \
            --image $GHCR_REPO/$BACKEND_IMAGE:latest
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Backend Container App with New Image
        run: |
          az containerapp update \
            --name $BACKEND_APP_NAME \
            --resource-group $RESOURCE_GROUP_NAME \
            --image $GHCR_REPO/$BACKEND_IMAGE:latest
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure Logout
        run: |
          az logout
        if: always()