name: Build and Push to GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'         # ✅ Only trigger if something in `app/` changes
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
  workflow_dispatch:      # ✅ Manual trigger option

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}
      RESOURCE_GROUP: rg-teqwerk-dev-westeurope-01
      LOCATION: centralus
      CONTAINERAPPS_ENVIRONMENT: appenv-teqwerk-dev-westeurope-01
      FRONTEND_IMAGE: frontend
      BACKEND_IMAGE: backend
      FRONTEND_APP_NAME: feapp-teqwerk-dev-westeurope-01
      BACKEND_APP_NAME: beapp-teqwerk-dev-westeurope-01

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $GHCR_REPO/$FRONTEND_IMAGE:latest ./app/frontend
          docker push $GHCR_REPO/$FRONTEND_IMAGE:latest

      - name: Build & Push Backend Image
        run: |
          docker build -t $GHCR_REPO/$BACKEND_IMAGE:latest ./app/backend
          docker push $GHCR_REPO/$BACKEND_IMAGE:latest